### ISSUE TITLE
Bugs about sit command

### ISSUE THREAD

**Issue by siulung201314** [SpraxDev/BetterChairs#106]
* **Server Version**: 1.16.5
* **Plugin Version**: 1.4.0-ALPHA

**Describe the bug**
1.
When a player uses sit command to sit down, he can sit successfully.
However, he still receives a message "You do not have permission to use this command."

2.
When a player sits on a shulker box and open it,
the box will push the player up and he keeps sitting on the air.

3.
When a player sits on a trapdoor,
he sit on the air above the trapdoor.

**To Reproduce**
1. stand on a shulker box or a trapdoor
2. use /sit command

**Comment by SpraxDev** [comment]
*It is generally a good idea to split every bug into its own issue (if they don't occur together or rely on each other) as it makes keeping track of them easier*

**Issue No. 1**
Should be fixed in the next update (0b31757f23c303a300820bd6541dce03b171738f)

**Issue No. 2 and 3**
I was able to confirm the bugs

**Comment by SpraxDev** [comment]
**Issue No. 2 and 3**
Bug should be fixed in the next release (fafe8152e18e523f3d4fd328a3e51f863046b6ae)
