### ISSUE TITLE
Off-Hand option & outdated Package

### ISSUE THREAD

**Issue by Sukram28** [SpraxDev/BetterChairs#89]
Hey there, first of thank you for the awesome plugin!

**1)** Is it possible to add an config option like this:

_When NeedEmptyHands enabled: Should we also check Emptiness of the Offhand?_
CheckEmptyOffhand: **true**

An option like this would help me a lot. With this option player could hold for example a totem or a bow in the offhand but could still sit down. I work with a lot of plugins that require holing things in the offhand. This would be a really cool feature :)

**2)** I'm getting some console infos that bother me a little. Is this fixable, or can I somehow turn this message off?

[NBTAPI] [NBTAPI] The NBT-API at 'package de.sprax2013.betterchairs.tr7zw.nbtapi' seems to be outdated!
[00:01:33 WARN]: [NBTAPI] [NBTAPI] Current Version: '2.6.0' Newest Version: 2.7.1'
[00:01:33 WARN]: [NBTAPI] [NBTAPI] Please update the nbt-api or the plugin that contains the api!

I'm not using any NBTAPI at all :/

Thanks for this remastered version. Really love it.
Greetings
Markus

**Comment by SpraxDev** [comment]
First, the warning about the outdated NBT-API. NBT-API is used by BetterChairs and included in it. I am aware of there being a newer version (#87) but the changes made to it do not affect BetterChairs, thus I'd have been updating it with the next release but not publish a new release because of it.

=> I've disabled the internal Update-Check for NBT-API and you won't be notified about them in the upcoming releases ^^

- - -

Now your feature request: I'll see what I can do. I can certainty add that option but I have to check why I was enforcing it in the first place. I'm not sure if there was a reason for it... But it'll probably be part of the next release

**Comment by Sukram28** [comment]
Ok thank you :)

**Comment by SpraxDev** [comment]
> => I've disabled the internal Update-Check for NBT-API and you won't be notified about them in the upcoming releases ^^

I've also removed the off-hand-empty-check. I'll publish the new release soon ^^
